/*
 * Copyright (C) 2022 Javier Marrero.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package cu.edu.cujae.graphy.swing;

import cu.edu.cujae.graphy.core.Graph;
import cu.edu.cujae.graphy.core.utility.Graphs;
import java.awt.BorderLayout;
import java.awt.Graphics;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Javier Marrero
 */
public class JGraphView extends JPanel
{
    
    private static final long serialVersionUID = 3455674585621L;
    
    private ConnectorFactory connectorFactory;
    private Graph<?> graph;

    /**
     * Creates new form JGraphView
     */
    public JGraphView()
    {
        this(null);
    }
    
    public JGraphView(Graph<?> graph)
    {
        initComponents();
        setGraph(graph);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrollableView = new JScrollPane();

        setLayout(new BorderLayout());

        scrollableView.setDoubleBuffered(true);
        scrollableView.setName("scrollableView"); // NOI18N
        add(scrollableView, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane scrollableView;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the graph
     */
    public Graph<?> getGraph()
    {
        return Graphs.makeImmutableGraph(graph);
    }

    /**
     * @param graph the graph to set
     */
    public void setGraph(
            Graph<?> graph)
    {
        this.graph = graph;
    }
}
